title: OCR Tagger
description: An Add-On that tags documents with the OCR engine used on them. 
instructions: ''
type: object
documents:
  - selected
  - query
properties: {}
categories: 
  - file
version: 2
